<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.29" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="150.0.7871.12400" />
    <PackageReference Include="Selenium.WebDriver.MSEdgeDriver" Version="150.0.4078.65" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LegacyAccessibilityCrawler.Core\LegacyAccessibilityCrawler.Core.csproj" />
    <ProjectReference Include="..\LegacyAccessibilityCrawler.Infrastructure\LegacyAccessibilityCrawler.Infrastructure.csproj" />
    <ProjectReference Include="..\LegacyAccessibilityCrawler.Reporting\LegacyAccessibilityCrawler.Reporting.csproj" />
  </ItemGroup>
</Project>
