name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore legacy-accessibility-static-crawler.sln

      - name: Build
        run: dotnet build legacy-accessibility-static-crawler.sln -c Release --no-restore

      - name: Test
        run: dotnet test legacy-accessibility-static-crawler.sln -c Release --no-build
